version: "3.5"

networks:
  time-series-admin:

volumes:
  time-series-admin:

services:
  ingress:
    networks:
      - time-series-admin

  time-series-admin:
    deploy:
      labels:
        - traefik.frontend.rule=$TIME_SERIES_ADMIN_ROUTING_LABEL
        - traefik.frontend.priority=$TIME_SERIES_ADMIN_ROUTING_LABEL_PRIORITY
        - traefik.port=80
        - ${TRAEFIK_BASIC_AUTH}
        - traefik.enable=true
        - traefik.tags=ingress 
        - traefik.docker.network=${STACK_NAME:-technocore}_time-series-admin
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      # Big services will need this modified or removed.
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    #environment:
      #- ADMIN_USER=${ADMIN_USER}
      #- ADMIN_PASSWORD={{"{{DOCKER-SECRET:admin_password}}"}}
    #image: ${image_provider:-scififarms}/technocore-time-series-admin:${TAG:-latest}
    image: timeseriesadmin/timeseriesadmin:0.1.9
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - time-series-admin
    #volumes:
      # Likely need to change this
      #- time-series-admin:/var/lib/time-series-admin
      #- ${DEV_MOUNT_TIME_SERIES_ADMIN_SHELL_MIGRATIONS:-$EMPTY_MOUNT}
